name       : kdoctools
version    : 5.39.0
release    : 8
source     :
    - https://download.kde.org/stable/frameworks/5.39/kdoctools-5.39.0.tar.xz : 57a12705b87754d8bbc76e3400691d02072d61bd0e2e4b62845dca558f9be49d
license    :
    - LGPL-2.1
    - MIT
component  : programming
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
