name       : kdoctools
version    : 5.52.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kdoctools-5.52.0.tar.xz : 368ef2d68a50ec006a6a05fbbd95574bb0620151b493d0fcdca32e964a2c2139
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
