name       : kdoctools
version    : 5.93.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/kdoctools-5.93.0.tar.xz : 25e83ff151c53667b94e25a5c41993796164683a43913820a5651f3610b65d5c
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
optimize   : lto
builddeps  :
    - pkgconfig(libxslt)
    - docbook-xml
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
