name       : kdoctools
version    : 5.59.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kdoctools-5.59.0.tar.xz : ec732210181d42a7dd61d66954f302afd4444e436081212a85e0e35c405c8e09
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
