name       : kdoctools
version    : 5.63.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kdoctools-5.63.0.tar.xz : a46a10424d6cd4dcb3d8a59b9fbd1bf9fe4f409af42decf853298b18bf4ecafe
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
