name       : kdoctools
version    : 5.74.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kdoctools-5.74.0.tar.xz : 4b54e7a7fb1328ceb4c0a95d620f226c8d8401f93ef28f165e37783b0ce3054e
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
