name       : kdoctools
version    : 5.71.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kdoctools-5.71.0.tar.xz : 1e2fcaa97a014e82f68c0c36591ce84568ead7abd59b66e534789103e162cd09
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
