name       : kdoctools
version    : 5.53.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kdoctools-5.53.0.tar.xz : 32d86563fe18abde8af6b93eaa5f3ff689e5783982a16ffe19e765631897514e
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
