name       : kdoctools
version    : 5.57.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/kdoctools-5.57.0.tar.xz : 649dbaff4f1559302e7da07f423a0bc9e3faa1c7a93dfeb170e50bf452d8def2
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
