name       : kdoctools
version    : 5.100.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/kdoctools-5.100.0.tar.xz : 40e9c9efb1374b7c2fd74ab5137fa14fa557fa4db4033483e3fae3a30da7272b
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
optimize   : lto
builddeps  :
    - pkgconfig(libxslt)
    - docbook-xml
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
