name       : kdoctools
version    : 5.105.0
release    : 71
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.105/kdoctools-5.105.0.tar.xz : 1b4e4b71914c46684219ba84fb4f8364809aeb43d74cfbe8f18ad53c728b0922
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
optimize   : lto
builddeps  :
    - pkgconfig(libxslt)
    - docbook-xml
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
