name       : kdoctools
version    : 5.47.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/kdoctools-5.47.0.tar.xz : e704ae597e05cb36ddab698a378edef59d718626275a16f3c02cc5460998f41b
license    :
    - LGPL-2.1
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
