name       : kdoctools
version    : 5.68.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/kdoctools-5.68.0.tar.xz : 93f5bee9dfaacacacfbeb3e915b192b5e645c1d01057b0cea4081c9ae5285670
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
