name       : kdoctools
version    : 5.72.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/kdoctools-5.72.0.tar.xz : 28836a88fd7107386b3a4c1037458d330d42dea7fa8213d06e9912dc5e19253b
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
