name       : kdoctools
version    : 5.45.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/kdoctools-5.45.0.tar.xz : a5322f7d09aa643d60738f3b24bda2d3c129cc9aa37856acf5bedba3929d4b2c
license    :
    - LGPL-2.1
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
