name       : kdoctools
version    : 5.69.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/kdoctools-5.69.0.tar.xz : 173a7f38c6bd77fc51e1a5f6d7053cc54e7f281f7ea6d9c6f356b12882c0d522
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
