name       : kdoctools
version    : 5.49.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/kdoctools-5.49.0.tar.xz : f4e9ffceb9c772e1d98fd3f3e26aa4ff64d64ac3f83e8830d0341c3d0a99b7b6
license    :
    - LGPL-2.1
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
