name       : kdoctools
version    : 5.64.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kdoctools-5.64.0.tar.xz : 3e669c9bdf8822c262d834a9fbe9250ffdc91ea49c916b2c16ac8483b62f8fce
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
