name       : kdoctools
version    : 5.28.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.28/kdoctools-5.28.0.tar.xz : ec90ee3e98914926a9c691d726ac9ee0d58831657ffeae508cb3bd7d7cafcdd6
license    :
    - LGPL-2.1
    - MIT
component  : programming
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
