name       : kdoctools
version    : 5.38.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.38/kdoctools-5.38.0.tar.xz : c95f7e604bd16c3ef97b3fc0320a5656ef1ea3b3c75b7d4d22348391423c7b39
license    :
    - LGPL-2.1
    - MIT
component  : programming
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
