name       : kdoctools
version    : 5.61.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.61/kdoctools-5.61.0.tar.xz : e48d8f8f075171c6b83189999a10552c772c6a7e9a115a2643414f9ecec77c6f
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
