name       : kdoctools
version    : 5.51.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kdoctools-5.51.0.tar.xz : bcc3ff9afb2a2be58179faae65a44ab65cdb7d4b2c014fa24a957e1330adee88
license    :
    - LGPL-2.1
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
