name       : kdoctools
version    : 5.92.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/kdoctools-5.92.0.tar.xz : 86a3aeb8b91dec0e1cd81b646654ebd750a8aedfac9b4d53b9b0019a91720870
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
optimize   : lto
builddeps  :
    - pkgconfig(libxslt)
    - docbook-xml
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
