name       : kdoctools
version    : 5.35.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.35/kdoctools-5.35.0.tar.xz : 0b7de7aa262db3a5981bc5cc496118ba968e129640ad92c7c9d76f5e026962e3
license    :
    - LGPL-2.1
    - MIT
component  : programming
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
