name       : kdoctools
version    : 5.84.0
release    : 56
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.84/kdoctools-5.84.0.tar.xz : 97e653793227600aec3a2236b61018e9c8c2fcfe5b73c94836f206ea558d0df4
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
optimize   : lto
builddeps  :
    - pkgconfig(libxslt)
    - docbook-xml
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
