name       : kdoctools
version    : 5.44.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kdoctools-5.44.0.tar.xz : 2316687ead1d11793670311f037c35e8535effe9e0967b143471e5ac92cdcc90
license    :
    - LGPL-2.1
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
