name       : kdoctools
version    : 5.56.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/kdoctools-5.56.0.tar.xz : e4f83bfaeca9ef89711577b756a3c359eb8d45b60a180934ba82431b5c36c007
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
