name       : kdoctools
version    : 5.25.0
release    : 2
source     :
    - http://download.kde.org/stable/frameworks/5.25/kdoctools-5.25.0.tar.xz : a00c43cf50d60374d62f1fa796033dbd5719eb0598328071092286052271947c
license    :
    - LGPL-2.1
    - MIT
component  : programming
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
