name       : kdoctools
version    : 5.109.0
release    : 74
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/kdoctools-5.109.0.tar.xz : a44e5b5e02ba5857d9dabe391672e889a1cbcd18e4b6a0794f9778af5250e69d
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
optimize   : lto
builddeps  :
    - pkgconfig(libxslt)
    - docbook-xml
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
