name       : kdoctools
version    : 5.50.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kdoctools-5.50.0.tar.xz : 1e37f26211160607ee825ae3b8f463e298958e59a3bd09e7948f62b4e271f2fd
license    :
    - LGPL-2.1
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
