name       : kdoctools
version    : 5.48.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/kdoctools-5.48.0.tar.xz : 688f76eb6a66f055f425ac94d756fbca173da9592c796f4db9e23f37510a1d6d
license    :
    - LGPL-2.1
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
