name       : kdoctools
version    : 5.66.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/kdoctools-5.66.0.tar.xz : 41e4ca7aceab17919ef4a82ad99606f520ebfe57f30205597b4184f7a3730a7a
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
