name       : kdoctools
version    : 5.85.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/kdoctools-5.85.0.tar.xz : c1c5505c42c221f2387b93e756c2d611f2494bb888af9c3d09993b57ccfd7d05
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
optimize   : lto
builddeps  :
    - pkgconfig(libxslt)
    - docbook-xml
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
