name       : kdoctools
version    : 5.60.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kdoctools-5.60.0.tar.xz : b231ea9857c5c1335fbf1a63907311a136651d93af4a4143e0b4caad833ae834
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming
optimize   : lto
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Help)
    - docbook-xml
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - perl-uri
rundeps    :
    - docbook-xml
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
