name       : kdoctools
version    : 5.36.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.36/kdoctools-5.36.0.tar.xz : 327b90bd7b9fae2455ef848f44709ec8dbead1f1a86ef169083e9000d2edfb69
license    :
    - LGPL-2.1
    - MIT
component  : programming
summary    : Create documentation from DocBook.
description: |
    Create documentation from DocBook
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Core)
    - docbook-xml
    - perl-uri
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
rundeps    :
    - docbook-xml
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
